
name: utests_on_pullreq # workflow name
on: # trigger
  pull_request:
    branches: [ master ]

# parallel jobs to perform
jobs:
  # === unittest execution ===
  unittest:
    runs-on: ubuntu-latest # runner
    
    steps: # tasks  
    - name: Set Github Workspace # access Github Workspace
      uses: actions/checkout@v2
    - name: Set up Python 3.x # set architecture and Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64' # architecture

    - name: Install dependencies # dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run unittests # run unittests
      run:
        python tests/test.py